url: "https://pages.git.daimler.com/plusng/template-react/"
markdown: kramdown
description: This coding guide describes additional pest practices well as DOs and DON'Ts not covered by the project template it belongs to.
